### PR TITLE
CF-468: add a task to upload jar to Veracode

### PR DESCRIPTION
**Pull request by shintasmith**
Adding Veracode task to upload scan, similar to cloudfeeds-atomhopper and atom-hopper

### CODE REVIEW

**Comment by shintasmith** [comment]
@usnavi, @ChandraAddala, please review.

**Comment by ChandraAddala** [comment]
Looks good.

**Comment by shintasmith** [comment]
ok to test

**Comment by shintasmith** [comment]
ok to test

**Comment by shintasmith** [comment]
@ChandraAddala, @usnavi, build break is fixed.

**Comment by ChandraAddala** [comment]
Looks good with the new changes.

**Pull request merged**
